insert into article (date, title, contents) values ('2017-02-18', 'Title 1', 'Contents 1');
insert into articlecomment (article_id, comment, importance) values (1, 'comments 1 for title 1', 4);
insert into articlecomment (article_id, comment, importance) values (1, 'comments 2 for title 1', 2);
insert into articlecomment (article_id, comment, importance) values (1, 'comments 3 for title 1', 1);
insert into article (date, title, contents) values ('2017-02-18', 'Title 2', 'Contents 2');
insert into article (date, title, contents) values ('2017-02-18', 'Title 3', 'Contents 3');
insert into article (date, title, contents) values ('2017-02-18', 'Title 4', 'Contents 4');
insert into articlecomment (article_id, comment, importance) values (4, 'comments 1 for title 4', 2);
insert into articlecomment (article_id, comment, importance) values (4, 'comments 2 for title 4', 1);
insert into article (date, title, contents) values ('2017-02-18', 'Title 5', 'Contents 5');
insert into articlecomment (article_id, comment, importance) values (5, 'comments 1 for title 5', 2);
insert into articlecomment (article_id, comment, importance) values (5, 'comments 2 for title 5', 1);
insert into articlecomment (article_id, comment, importance) values (5, 'comments 3 for title 5', 2);
insert into articlecomment (article_id, comment, importance) values (5, 'comments 4 for title 5', 1);
insert into article (date, title, contents) values ('2017-02-18', 'Title 6', 'Contents 6');
